flussdata/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'flussdata'

urlpatterns = [
    path('query', views.query, name='query'),
    path('modify', views.modify, name='modify'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('query/station<int:station_id>', views.station_data, name='station_data'),
    path('modify/upload/', views.upload_file, name='modify/upload'),
    path('modify/upload/success_upload/', views.success_upload, name='success_upload'),
    path('helpers/', views.helpers, name='helpers'),
    path('accounts/', include("django.contrib.auth.urls")),  # new
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
from django.views.defaults import permission_denied

# added app views:
from riveranalyst import views as river_views

urlpatterns = [
    path('', river_views.home, name='home'),
    path('admin/doc/', include('django.contrib.admindocs.urls')),  # MUST come before path(admin)
    path('admin/', admin.site.urls),
    path('riveranalyst/', include('riveranalyst.urls')),
    path('sedimentanalyst/', include('sedimentanalyst.urls')),
    path('accounts/login/', auth_views.LoginView.as_view()),
    path('__debug__/', include('debug_toolbar.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    *static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0]),
    # Serve static files from the app's static directory
    path('static/examples', serve, {'document_root': 'static'}),
    ]

flussdata/views.py
from django.shortcuts import render
import flussdata.tables as flutb
from .filters import *
from .forms import *
from plotly.offline import plot
from django_pandas.io import read_frame
from django_tables2.config import RequestConfig
from django_tables2.export.export import TableExport
from django.http import JsonResponse
from flussdata.utils.tables_append import append_db
from flussdata.utils.plotter import plot_gsd, plot_ido, plot_map, plot_kf
from django.contrib.auth.decorators import login_required, permission_required
import pandas as pd


def home(request):
    total_subsurf = SubsurfaceSed.objects.count()
    total_surf = SurfaceSed.objects.count()
    total_idoc = IDO.objects.values_list('sample_id').distinct().count()
    total_kf = Kf.objects.values_list('sample_id').distinct().count()
    total_v = Hydraulics.objects.count()

    context = {'navbar': 'home',
               'total_subsurf': total_subsurf,
               'total_surf': total_surf,
               'total_idoc': total_idoc,
               'total_kf': total_kf,
               'total_v': total_v}
    return render(request, 'home.html', context)


@login_required
@permission_required('flussdata.view_collecteddata', raise_exception=True)
def query(request):
    #  Get all measurement data from the table
    subsurf_objects = SubsurfaceSed.objects.all()
    surf_objects = SurfaceSed.objects.all()
    idoc_objects = IDO.objects.all()
    station_objects = MeasStation.objects.all()
    kf_objects = Kf.objects.all()
    v_objects = Hydraulics.objects.all()

    # Get filter if the user selected any from the listed in filters.py
    # subSurfFilter = SubSurfFilter(request.GET, queryset=subsurf_objects)
    stFilter = StationFilter(request.GET, queryset=station_objects)

    # Apply filter, remaking the object
    # subsurf_objects = subSurfFilter.qs
    station_objects = stFilter.qs
    subsurf_objects = subsurf_objects.filter(meas_station__name__in=station_objects.values('name'))

    idoc_objects = idoc_objects.filter(meas_station__name__in=station_objects.values('name'))
    surf_objects = surf_objects.filter(meas_station__name__in=station_objects.values('name'))
    kf_objects = kf_objects.filter(meas_station__name__in=station_objects.values('name'))
    v_objects = v_objects.filter(meas_station__name__in=station_objects.values('name'))

    # creates df from filtered table
    df_stations = read_frame(station_objects)

    # Shows the table from the flussdata tables, hosted on tables.py
    subsurf_tb_show = flutb.SubsurfaceTable(subsurf_objects).paginate(per_page=10)
    surf_tb_show = flutb.SurfaceTable(surf_objects).paginate(per_page=10)
    idoc_show = flutb.IDOCTable(idoc_objects).paginate(per_page=10)
    station_show = flutb.StationTable(station_objects).paginate(per_page=10)
    kf_show = flutb.KfTable(kf_objects).paginate(per_page=10)

    # Count the number of samples alter filte ris applied
    subsurf_count = subsurf_objects.count()
    surf_count = surf_objects.count()
    kf_count = kf_objects.values_list('sample_id').distinct().count()
    v_count = v_objects.count()
    idoc_count = idoc_objects.values_list('sample_id').distinct().count()

    # create new columns with computed lat and log in the projection
    # accepted by the mapbox (epsg:4326)

    # creates fig for mapbox using the df created from the filtered table
    fig = plot_map(df_stations)

    # mapbox div
    mapboxdiv = plot(fig, output_type='div')

    # export of sub. sed. table
    RequestConfig(request).configure(subsurf_tb_show)
    export_format = request.GET.get("_export", None)

    RequestConfig(request).configure(surf_tb_show)
    export_format_surf = request.GET.get("_export_surf", None)

    RequestConfig(request).configure(station_show)
    export_format_st = request.GET.get("_export_st", None)

    RequestConfig(request).configure(idoc_show)
    export_format_idoc = request.GET.get("_export_idoc", None)

    RequestConfig(request).configure(kf_show)
    export_format_kf = request.GET.get("_export_kf", None)

    if TableExport.is_valid_format(export_format):
        exporter = TableExport(export_format, subsurf_tb_show)
        return exporter.response("subsurface-samples.{}".format(export_format))

    if TableExport.is_valid_format(export_format_surf):
        exporter = TableExport(export_format_idoc, idoc_show)
        return exporter.response("surface-samples.{}".format(export_format_idoc))

    if TableExport.is_valid_format(export_format_st):
        exporter = TableExport(export_format_st, station_show)
        return exporter.response("stations.{}".format(export_format_st))

    if TableExport.is_valid_format(export_format_idoc):
        exporter = TableExport(export_format_idoc, idoc_show)
        return exporter.response("idoc.{}".format(export_format_idoc))

    if TableExport.is_valid_format(export_format_kf):
        exporter = TableExport(export_format_kf, kf_show)
        return exporter.response("kf.{}".format(export_format_kf))

    #  return this to the context
    context = {'title': 'Flussdata: Query',  # pagetitle
               'navbar': 'activequery',  # make the tab 'query' highlighted

               # number of measurements for the selected query
               'subsurf_count': subsurf_count,
               'surf_count': surf_count,
               'idoc_count': idoc_count,
               'kf_count': kf_count,
               'v_count': v_count,

               # filters
               # 'subSurfFilter': subSurfFilter,
               'stFilter': stFilter,
               # 'idocFilter': idocFilter,

               # tables
               'subsurf_tb_show': subsurf_tb_show,
               'idoc_table': idoc_show,
               'station_table': station_show,
               'surf_tb_show': surf_tb_show,
               'kf_table': kf_show,

               # mapbox
               'mapboxfig': mapboxdiv}

    return render(request, 'flussdata/query.html', context)


@login_required
@permission_required('flussdata.view_collected_data', raise_exception=True)
def station_data(request, station_id):
    #  Get all measurement data from the table
    gsds = []
    station = MeasStation.objects.get(id=station_id)
    subsurf_sample = SubsurfaceSed.objects.filter(meas_station=station_id)
    surf_sample = SurfaceSed.objects.filter(meas_station=station_id)

    if surf_sample:
        fig_surf = plot_gsd(surf_sample, title='Surface Grain Size Distribution')
        # return graph div
        plot_div = plot(fig_surf, output_type='div')
        gsds.append(plot_div)

    if subsurf_sample:
        fig_subsurf = plot_gsd(subsurf_sample, title='Subsurface Grain Size Distribution')
        # return graph div
        plot_div = plot(fig_subsurf, output_type='div')
        gsds.append(plot_div)

    # generating fig for idocs
    idocs = IDO.objects.filter(meas_station_id=station_id)
    if idocs:
        fig_idoc = plot_ido(idocs)
        idoc_div = plot(fig_idoc, output_type='div')
    else:
        idoc_div = None

    # generating fig for kf
    kfs = Kf.objects.filter(meas_station_id=station_id)
    if kfs:
        fig_kf = plot_kf(kfs)
        kf_div = plot(fig_kf, output_type='div')
    else:
        kf_div = None
    context = {'gsds': gsds, 'idoc_div': idoc_div, 'kf_div': kf_div, 'station_name': station.name}
    return render(request, 'flussdata/station_data.html', context)


@login_required
@permission_required('flussdata.add_collected_data', raise_exception=True)
def modify(request):
    context = {'title': 'Flussdata: Modify',
               'form': FileForm,
               'navbar': 'activemodify'}
    return render(request, 'flussdata/modify.html', context)


@login_required
@permission_required('flussdata.add_collected_data', raise_exception=True)
def upload_file(request):
    global MESSAGE
    MESSAGE = 'Fail: Please select the collected data.'
    if request.method == 'POST':
        if request.POST['collected_data']:
            try:
                my_file = request.FILES['file']  # gets the table file from the post request
                df = pd.read_csv(my_file.temporary_file_path(), encoding='utf-8',
                                 parse_dates=['date'])

                #  append data from df read into the database
                append_db(request.POST['collected_data'], df)
                MESSAGE = 'Success: File was parsed and appended to the database.'
            except Exception as e:
                # TODO
                # send message to user to make him selecte a collected data
                MESSAGE = 'Fail: File could not be parsed and appended ' \
                          'to the database. Error messages: \n' + str(e)
    return JsonResponse({'post': 'false'})


@login_required
@permission_required('flussdata.add_collected_data', raise_exception=True)
def success_upload(request):
    return render(request, 'flussdata/success_upload.html', {'message': MESSAGE})


def dashboard(request):
    context = {'title': 'Flussdata: Dashboard',  # pagetitle
               'navbar': 'activedash',  # make the tab 'query' highlighted
               }
    return render(request, 'flussdata/dashboard.html', context)


def helpers(request):
    context = {'title': 'Flussdata: Helpers',  # pagetitle
               'navbar': 'activehelpers',  # make the tab 'query' highlighted
               }
    return render(request, 'flussdata/helpers.html', context)

flussdata/templates/flussdata/helpers.html
{% extends 'base.html' %}
{% load static %}
{% load django_tables2 %}

{% block head %}
<link rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.6.0/styles/default.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.6.0/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>

<!--&lt;!&ndash; then add this badge component &ndash;&gt;-->
<script src="https://cdn.jsdelivr.net/npm/highlightjs-badgejs@0.0.5/highlightjs-badgejs.min.js"></script>

{% endblock%}

{% block content %}
<div class="card card-body">
    <div class="row">
        <div class="col-md-2">
            <div class="row text-center">
                <div class="col">
                    <a href="https://sedimentanalyst.herokuapp.com/"><img src="{% static 'images/sed-analyst.jpg' %}"
                                                                          alt="Sedimentanalyst" width="215"></a>
			    </div>
            </div>
        </div>
        <div class="col-md-4">
            <div>
                <p>
                    The analysis of sieving tests and dataset wrangling is a pre-requisite for feeding the database with
                    surface and subsurface sedimentological data.

                </p>
                <p>
                    Sediment Analyst is an open-source web app that helps
                    dealing with sieving datasets and formatting them in the typical way (feature columns and
                    observations, a.k.a. sample rows) for data science and database management.
                </p>
            </div>
        </div>
        <div class="col-md-6">
            <p>Alternatively to the web, run the app locally without the need to loading your dataset to the internet
                by cloning the git repository:</p>
            <pre><code class="git">
        git clone https://github.com/beatriznegreiros/sediment-analyst.git
            </code></pre>
        </div>
    </div>
</div>
<br>
<div class="card card-body">
    <div class="row">
        <div class="col-md-4">
            <div>
                <h2>Merging tables</h2>
                <p>
                    Merging tables is an essential database task. Tables can be easily merged with
                    SQL or SQL-like python functions. The <a href="https://pandas.pydata.org/">
                    pandas</a> library offers multiple SQL-like and data table management functions.
                </p>
                <p>
                    The code snippet at the right shows how to merge IDO and kf tables, which are available
                    for download in the <a href="{% url 'flussdata:query' %}">Query</a> tab.
                </p>
            </div>
        </div>
        <div class="col-md-8">
            <pre>
                <code class="python">
        import pandas as pd

        # reading csvs
        kf_df = pd.read_csv('path/to/kf/csv/')
        idoc_df = pd.read_csv('path/to/idoc/csv')
        st_df = pd.read_csv('path/to/stations/csv')

        # use how=outer is to ensure the union instead of intersection of the two dfs
        # step 1: merge kf and idoc tables by linking the rows both through sample_id
        # and dp_position
        kf_idoc = ido_df.merge(kf_df, on=['sample_id', 'dp_position'], how='outer')
        kf_idoc = kf_idoc.drop_duplicates(subset=['sample_id', 'dp_position'])

        # step 2: merge kf_idoc table to the stations information by linking the rows
        # through the measurement station
        kf_idoc_st = st_df.merge(ido_df, left_on='name', right_on='meas_station')

        # save merged table
        kf_idoc_st.to_csv('merge-kf-idoc-st.csv')
            </code>
            </pre>
        </div>
    </div>
</div>


{% endblock %}

flussdata/templates/flussdata/main.html
{% extends 'base.html' %}
{% block content %}

<h1>Flussdata Main Page</h1>
<h3>Functions</h3>
<ul>
    <li> <a href="{% url 'home' %}">Home </a></li>
    <li> <a href="{% url 'flussdata:main' %}"> Flussdata Main Page </a></li>
</ul>

<p>
    <input type="checkbox" name="class1"><br>
    Freezecore </p><br>

    <p><label for="inp06"> Which Database:
        <select name="meas-table" id="inp05">
            <option value=""> -- Please select -- </option>
            <option value="slurp-drop"> Slurping </option>
            <option value="fc-drop">Freezecore</option>
        </select>
    </label>
    </p>


    <form action="upload" method="POST" class="dropzone">
        {%csrf_token%}
        <div class="fallback">
            <input name="table_fc" type="file" multiple />
        </div>
    </form>



{% endblock %}

flussdata/templates/flussdata/modify.html
{% extends 'base.html' %}

{% block content %}

<!--{% if user.is_authenticated %}-->

    <br>
        <!--    DRAG AND DROP ZONE-->
        <script src="https://rawgit.com/enyo/dropzone/master/dist/dropzone.js"></script>
        <link rel="stylesheet" href="https://rawgit.com/enyo/dropzone/master/dist/dropzone.css">
        <h2>Upload area</h2>
        <div>
            <p>For adding data to the DB, follow these steps:
            <ol>
                <li>Important: use only the template csvs as shown in the  <a href="query">query tab </a>. Swapping column
                    positions or leaving selected fields blank is not a problem, but don't remove nor rename any
                    column names.</li>
                <li>First, upload the general information regarding the measurement points (option 'Stations') using
                the appropriate template csv. Name the "measurement stations" carefully. They will link
                the database across multiple tables to gather parametrical data for that measurement point. </li>
                <li>Upload the collected data (following the corresponding template) by selecting the data type and
                    uploading the csv in the dropzone below. As long as the measurement stations (step 2) are
                uploaded to the database, the order for uploading the remaining parametrical data doensn't matter.
                    Important: <b>the measurement station of the parametrical data needs to exactly match one of the
                        "meas_station" you provided in step 2, otherwise an error message will be shown. </b></li>
            </ol>

            Alternatively, the DB can also be managed in the admin page (link <a href="/admin">here</a>). </p>

        </div>
        <div class="row">
            <div class="col-md">
                <div class="card card-body">
                    <form action="modify/upload/" method="POST" class="dropzone dz" id="my-dropzone">
                        {%csrf_token%}
                        {{ form.as_p }}
                        <div class="fallback">
                            <input name="file" type="file" multiple />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    <br>
    <div class="row">
        <br>
        <p><a href="{% url 'flussdata:logout' %}?next={{ request.path }}"><button class="btn btn-primary">Log out</button></a></p>
    </div>

<!--{% else %}-->
<!--    <div class="card card-body">-->
<!--        <h2>User Authentication Required </h2>-->
<!--        <p><a href="{% url 'flussdata:login' %}?next={{ request.path }}">Login</a> to have access to the database.</p>-->
<!--    </div>-->
<!--{% endif %}-->



{% endblock %}

flussdata/templates/flussdata/query.html
{% extends 'base.html' %}
{% load django_tables2 %}

{% block content %}
<!--{% if user.is_authenticated %}-->
<br>
<div class="row">

    <div class="col-md">
        <div class="row">
            <div class="col-md">
                <div class="card card-body">
                <h3>Filter by stations</h3>
                    <form method="get">
                        {{ stFilter.form.as_p }}
                        <button class="btn btn-primary" type="submit">Search</button>
                    </form>
                </div>
            </div>

        </div>

        <br>
        <div class="row">
            <div class="col-md-3">
                <div class="card text-center text-white  mb-3" id="total-orders">
                    <div class="card-header">
                        <h5 class="card-title">Subsurface/ Surface Sediment Samples</h5>
                    </div>
                    <div class="card-body">
                        <h3 class="card-title">{{subsurf_count}}/ {{surf_count}}</h3>
                    </div>
                </div>
                <div class="card text-center text-white  mb-3" id="orders-delivered">
                    <div class="card-header">
                        <h5 class="card-title">IDO/ kf Depth Profiles</h5>
                    </div>
                    <div class="card-body">
                        <h3 class="card-title">{{idoc_count}}/ {{kf_count}}</h3>
                    </div>
                </div>
                <div class="card text-center text-white  mb-3" id="orders-pending">
                    <div class="card-header">
                        <h5 class="card-title">Points of Hydraulic Measurements</h5>
                    </div>
                    <div class="card-body">
                        <h3 class="card-title">{{v_count}}</h3>
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                <div class="card card-body">
                {% autoescape off %}
                    {{ mapboxfig }}
                {% endautoescape %}
                </div>
            </div>
	    </div>
        <br>
        <div class="row">
            <div class="card card-body">
                <h3>Measurement Stations</h3>

                {% render_table station_table %}
                <div class="margin-right">
                    <a href="{% querystring '_export_st'='csv' %}"><button class="btn btn-primary">Download CSV</button></a>
                    <a href="{% querystring '_export_st'='xlsx' %}"><button class="btn btn-primary">Download XLSX</button></a>
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="card card-body">
                <h3>Subsurface Sediment Samples</h3>

                {% render_table subsurf_tb_show %}
                <div class="margin-right">
                    <a href="{% querystring '_export'='csv' %}"><button class="btn btn-primary">Download CSV</button></a>
                    <a href="{% querystring '_export'='xlsx' %}"><button class="btn btn-primary">Download XLSX</button></a>
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="card card-body">
                <h3>Surface Sediment Samples</h3>

                {% render_table surf_tb_show %}
                <div class="margin-right">
                    <a href="{% querystring '_export'='csv' %}"><button class="btn btn-primary">Download CSV</button></a>
                    <a href="{% querystring '_export'='xlsx' %}"><button class="btn btn-primary">Download XLSX</button></a>
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="card card-body">
                <h3>Intragravel Dissolved Oxygen (IDO)</h3>
                {% render_table idoc_table %}
                <div class="margin-right">
                    <a href="{% querystring '_export_idoc'='csv' %}"><button class="btn btn-primary">Download CSV</button></a>
                    <a href="{% querystring '_export_idoc'='xlsx' %}"><button class="btn btn-primary">Download XLSX</button></a>
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="card card-body">
                <h3>Hydraulic Conductivity (kf) </h3>
                {% render_table kf_table %}
                <div class="margin-right">
                    <a href="{% querystring '_export_kf'='csv' %}"><button class="btn btn-primary">Download CSV</button></a>
                    <a href="{% querystring '_export_kf'='xlsx' %}"><button class="btn btn-primary">Download XLSX</button></a>
                </div>
            </div>
        </div>

    </div>
</div>
<br>
<div class="row">
    <p><a href="{% url 'flussdata:logout' %}?next={{ request.path }}"><button class="btn btn-primary">Log out</button></a></p>
</div>

<!--{% else %}-->
<!--<div class="card card-body">-->
<!--    <h2>User Authentication Required </h2>-->
<!--    <p><a href="{% url 'flussdata:login' %}?next={{ request.path }}">Login</a> to have access to the database.</p>-->
<!--</div>-->
<!--{% endif %}-->
{% endblock %}