project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
from django.views.defaults import permission_denied

# added app views:
from riveranalyst import views as river_views

urlpatterns = [
    path('', river_views.home, name='home'),
    path('admin/doc/', include('django.contrib.admindocs.urls')),  # MUST come before path(admin)
    path('admin/', admin.site.urls),
    path('riveranalyst/', include('riveranalyst.urls')),
    path('sedimentanalyst/', include('sedimentanalyst.urls')),
    path('accounts/login/', auth_views.LoginView.as_view()),
    path('__debug__/', include('debug_toolbar.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    *static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0]),
    # Serve static files from the app's static directory
    path('static/examples', serve, {'document_root': 'static'}),
    ]

riveranalyst/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.defaults import permission_denied

app_name = 'riveranalyst'

urlpatterns = [
    path('query', views.query, name='query'),
    path('modify', views.modify, name='modify'),
    path('analysis', views.analysis, name='analysis'),
    path('query/position<int:position_id>', views.position_data, name='position_data'),
    path('modify/upload/', views.upload_file, name='modify/upload'),
    path('modify/upload/success_upload/', views.success_upload, name='success_upload'),
    path('accounts/', include("django.contrib.auth.urls")),  # new
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

sedimentanalyst/urls.py
from django.urls import path
from . import views
from sedimentanalyst.app import web_application

app_name = 'sedimentanalyst'

urlpatterns = [
    path('', views.app, name='app'),
]

templates/base.html
{% load static %}
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">

<!--      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">-->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">


      <!--    Custom css & js (dropzone)-->
      <script src="{% static 'main.js' %}" defer></script>
      <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">

      <!--    for Dash to work-->
      <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

    <!-- favicon TO DO -->
    <link rel="shortcut icon" type="image/png" href="{% static 'images/rio-logo-white.png' %}"/>
    <!-- INSERT ADITIONAL INFORMATION TO THE HEAD TAG HERE-->
      {% block head %}
      {% endblock%}

    <!-- CHANGES THE PAGE TITLE IF THE VARIABLE "title" IS PASSED BY THE VIEW -->
    {% if title %}
        <title>{{title}}</title>
    {% else %}
    <!-- USE DEFAULT TITLE TEXT IF NO VARIABLE "title" IS PASSED BY THE VIEW -->
        <title>River Analyst</title>
    {% endif %}

  </head>
  <body>
    <!-- BOOTSTRAP NAVBAR CODE -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <img style="height: 70" src="{% static 'images/rio-logo-and-text-white.png' %}">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link {% if navbar == 'home' %} active {% endif %}" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if navbar == 'activedash' %} active {% endif %}" href="{% url 'riveranalyst:analysis' %}">Analysis</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if navbar == 'activequery' %} active {% endif %}" href="{% url 'riveranalyst:query' %}">Query</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if navbar == 'activemodify' %} active {% endif %}" href="{% url 'riveranalyst:modify' %}">Upload</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if navbar == 'activesed' %} active {% endif %}" href="{% url 'sedimentanalyst:app' %}">Sediment</a>
                </li>

            </ul>
        </div>
    </nav>

    <!-- END OF NAVBAR CODE-->


    <div class="container-fluid mt-5" style="max-width: 80%">
    <!-- INSERT THE CONTENT FROM SPECIFIC PAGES HERE-->
        {% block content %}
        {% endblock  %}
    </div>
    <br>
    <br>
    <br>
    <br>
<!-- Footer -->
  <footer class="bg-white">
    <div class="container py-5">
      <div class="row py-4">
        <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">

<!--          <ul class="list-inline mt-4">-->
            <h1><a href="https://github.com/riveranalyst"><i class="icon ion-social-github"></i></a></h1>
            <p class="text-muted">River Analyst Team</p>
            <!--            <li class="list-inline-item"><a href="#" target="_blank" title="pinterest"><i class="fa fa-pinterest"></i></a></li>-->
<!--            <li class="list-inline-item"><a href="#" target="_blank" title="vimeo"><i class="fa fa-vimeo"></i></a></li>-->
<!--          </ul>-->
        </div>
        <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
          <h6 class="text-uppercase font-weight-bold mb-4">Contributors</h6>
          <ul class="list-unstyled mb-0">
            <li class="mb-2"><a href="https://beatriznegreiros.com/" class="text-muted">Beatriz Negreiros</a></li>
            <li class="mb-2"><a href="https://sebastian-schwindt.org/" class="text-muted">Sebastian Schwindt</a></li>
            <li class="mb-2"><a href="https://www.linkedin.com/in/federica-scolari-81b6a214b/" class="text-muted">Federica Scolari</a></li>
            <li class="mb-2"><a href="https://ricardovobarros.github.io/" class="text-muted">Ricardo Barros</a></li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
          <h6 class="text-uppercase font-weight-bold mb-4">About</h6>
          <ul class="list-unstyled mb-0">
            <li class="mb-2"><a href="https://www.iws.uni-stuttgart.de/lww/" class="text-muted">Department of Hydraulic Engineering and Water Resources Management</a></li>

          </ul>
        </div>
        <div class="col-lg-4 col-md-6 mb-lg-0">
          <h6 class="text-uppercase font-weight-bold mb-4">Get in touch</h6>
          <p class="text-muted mb-4"></p>
<!--          <div class="p-1 rounded border">-->
            <p><a href="mailto:beatriz.negreiros@iws.uni-stuttgart.de">beatriz.negreiros@iws.uni-stuttgart.de</a></p>
            <p><a href="mailto:sebastian.schwindt@iws.uni-stuttgart.de">sebastian.schwindt@iws.uni-stuttgart.de</a></p>

        </div>
      </div>
    </div>

    <!-- Copyrights -->
    <div class="bg-light py-4">
      <div class="container text-center">
        <p class="text-muted mb-0 py-2">© River Analyst Team. All rights reserved.</p>
      </div>
    </div>
  </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />

<style>
      .header-icon {
        display: inline-flex; /* display icon and text inline */
        align-items: center; /* center vertically */
        gap: 10px; /* add some space between icon and text */
      }
</style>

{% endblock%}


{% block content %}

<div class="row">
    <div class="col-md">
        <div class="card card-body">

            <h2>Welcome</h2>
            <p>River Analyst is a web app featuring a novel database approach for leveraging hydro-environmental analyses of
				exponentially-growing, dataype diverse river data. To-date investigations of our field team resulted in an unprecedented
				open-source river database that can be queried and visualized for free (<a href="riveranalyst/query">Query</a> and <a href="riveranalyst/analysis">Analysis</a> tabs).
            </p>
            <p>
				Access to the data upload feature (<a href="riveranalyst/modify">Upload</a> tab) is restricted to authorized users only.
				User credentials can be obtained through our team to enable research collaboration.
				To request access, please contact us via the email addresses listed on the footer of
				this page.
			</p>

<!--			<p><a href="mailto:beatriz.negreiros@iws.uni-stuttgart.de"><button class="btn btn-primary" type="submit">Get in touch</button></a></p>-->
        </div>

    </div>
</div>

<br>

<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title">Subsurface/ Surface Sediment Samples</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{total_subsurf}}/ {{total_surf}}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5 class="card-title">IDO/ kf Depth Profiles</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{total_idoc}}/ {{total_kf}}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h5 class="card-title">Points of Hydraulic Measurements</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{total_v}}</h3>
			  	</div>
			</div>
		</div>
	</div>

</div>
<br>
<div class="row">
	<div class="col-md">
		<div class="header-icon">
			<i class="fas fa-thin fa-lightbulb fa-3x"></i><h4>Use River Analyst locally</h4>
			<div>
					<p>
					River Analyst is also integrated into an open-source framework that caters to organizations seeking to maintain their databases locally. This framework offers greater flexibility and control over data management.
					</p>
					<p>
					Visit <a href="https://riveranalyst.github.io/">https://riveranalyst.github.io/</a> for detailed instructions and get started.
					</p>
			</div>
		</div>
	</div>
</div>
<br>
<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h2>Description of measuring methods</h2>
			<p><h4> Surface and subsurface sediment sampling</h4></p>
				<p>Sediment sampling involve collecting sediments with the help of shovels, for instance, and bringing them to the lab for
					drying (conventionally at 105 °C for 24 h) and subsequent dry sieving with sieves according to the <a href="https://www.journals.uchicago.edu/doi/epdf/10.1086/622910">Wentworth (1922)</a> scale.
					Sieving analyses of surface and subsurface samples from the overlayer and underlayer, respectively,
					enable to derive several sedimentological parameters that characterize the substrate. Another method for
					subsurface sampling is the freeze core method <a href="https://www.sciencedirect.com/science/article/pii/0037073881900099">(Carling & Reader, 1981)</a>, which involves pulling out frozen sediment samples from the riverbed with a tripod.
				</p>
			<p><h4>MultiPAC for substrate assessment</h4></p>
				<p>MultiPAC (<a href="https://onlinelibrary.wiley.com/doi/10.1002/rra.4145">Negreiros et al., 2023</a>; <a href="https://henry.baw.de/bitstream/20.500.11970/107414/1/276_Mitteilungen_UniStuttgart_Seitz.pdf">Seitz, 2020</a>) is a multi-parameter approach to assess riverbed clogging and vertical hyporheic connectivity, which consists of
					measuring multiple riverbed physico-chemical parameters, namely riverbed:
					<ul>
						<li>grain size characteristics </li>
						<li>porosity</li>
						<li>interstitial dissolved oxygen (IDO)</li>
						<li>hydraulic conductivity (kf) </li>
					</ul>
				The grain size and riverbed porosity are derived from freeze cores and represent bulk parameter
		values for a given xy measurement point. The interstitial dissolved oxygen (IDO) and hydraulic conductivity
		(kf) are measured as vertical profiles along the riverbed depth and thus enable to locate depths layers with
		low hyporheic habitat quality.
			</p>

			<div class="row text-center">
				<div class="col-md"><img src="{% static 'images/slurp-pic.jpg' %}" alt="Slurp" width="500"><p>Measuring setup for the hydraulic conductivity (kf)</p></div>

				<div class="col-md"><img src="{% static 'images/fieldwork.jpg' %}" alt="Fieldwork" width="520"><p>Measuring setup for the hydraulic conductivity (left) freeze core method (right)</p></div>
			</div>

			<p><h4>In-situ flow velocity measurements</h4></p>

				<p>Acoustic Doppler Velocimeter (ADV) devices (e.g., Flowtracker2, SonTek) enables to determine
					multi-dimensional flow velocity vectors (x, y, and z) of surface flow. This data is crucial for the
					validation of hydrodynamic numerical models. Additional hydrodynamic data, such as turbulent kinetic
					energy (TKE), can be derived from measured temporal velocity fluctuations to investigate morphological
					features for habitat enhancement.
				</p>
				<p>The FlowTracker2 uses acoustic Doppler technology to measure velocity at multiple points in a water column.
					The device consists of a handheld unit that houses the electronics and transducers, and a set of probes
					that are inserted into the water to take velocity measurements. The device can measure velocity in both
					shallow and deep water, and is suitable for a range of applications, in particular river or stream gauging.

				</p>




<!--			<p><a href="mailto:beatriz.negreiros@iws.uni-stuttgart.de"><button class="btn btn-primary" type="submit">Get in touch</button></a></p>-->
        </div>
		<br>


    </div>
</div>


<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <p><h2>Selected publications</h2></p>
            <p class="link"><a href="https://onlinelibrary.wiley.com/doi/10.1002/rra.4145"> Negreiros, B., Aybar Galdos, A., Seitz, L., Noack, M., Schwindt, S., Wieprecht, S., & Haun, S. (2023) A multi-parameter approach to quantify riverbed clogging and vertical hyporheic connectivity. River Research and Applications. doi: 10.1002/rra.4145 </a></p>
			<p class="link"><a href="https://www.research-collection.ethz.ch/handle/20.500.11850/513098"> Kunz, M., Negreiros, B., Schwindt, S., Haun, S., Noack, M., and Wieprecht, S. (2021) Inn-ovative morphological restoration efforts. International Symposium on Bedload Management. doi: 10.3929/ethz-b-000513098 </a></p>
			<p class="link"><a href="https://henry.baw.de/bitstream/20.500.11970/107414/1/276_Mitteilungen_UniStuttgart_Seitz.pdf">Seitz, L. (2020). Development of new methods to apply a multiparameter approach-a first step towards the determination of colmation. PhD Thesis. doi: 0.18419/opus-11249 </a></p>
			<p class="link"><a href="https://www.sciencedirect.com/science/article/abs/pii/S0169555X18300278">Seitz, L., Haas, C., Noack, M., & Wieprecht, S. (2018). From picture to porosity of river bed material using Structure-from-Motion with Multi-View-Stereo. Geomorphology. doi: 10.1016/j.geomorph.2018.01.014</a></p>

<!--			<p><a href="mailto:beatriz.negreiros@iws.uni-stuttgart.de"><button class="btn btn-primary" type="submit">Get in touch</button></a></p>-->
        </div>

    </div>
</div>

<br>

<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h2>Disclaimer</h2>
			<p>No warranty is expressed or implied regarding the usefulness or completeness of the information and documentation provided. References to commercial products do not imply endorsement by the Author. The concepts, materials, and methods used in the algorithms and described in the documentation are for informational purposes only. The Author has made substantial effort to ensure the accuracy of the algorithms and the documentation, but the Author shall not be held liable, nor his employer or funding sponsors, for calculations and/or decisions made on the basis of application of the scripts and documentation. The information is provided “as is” and anyone who chooses to use the information is responsible for her or his own choices as to what to do with the data. The individual is responsible for the results that follow from their decisions.</p>
			<br>
			<p>This web site contains external links to other, external web sites and information provided by third parties. There may be technical inaccuracies, typographical or other errors, programming bugs or computer viruses contained within the web site or its contents. Users may use the information and links at their own risk. The Author of this web site excludes all warranties whether express, implied, statutory or otherwise, relating in any way to this web site or use of this web site; and liability (including for negligence) to users in respect of any loss or damage (including special, indirect or consequential loss or damage such as loss of revenue, unavailability of systems or loss of data) arising from or in connection with any use of the information on or access through this web site for any reason whatsoever (including negligence).</p>

		</div>

    </div>
</div>


{% endblock %}